server:
  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/openbao/data"
      }

  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: local-path

  securityContext:
    pod:
      fsGroup: 1000
      runAsNonRoot: true
    container:
      runAsUser: 100
      runAsNonRoot: true
      allowPrivilegeEscalation: false

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: bao.rosta.dev
        paths:
          - /
    tls:
      - hosts:
          - bao.rosta.dev

  # HA disabled for single node
  ha:
    enabled: false

ui:
  enabled: true
  serviceType: ClusterIP

injector:
  enabled: false
