replicaCount: 1

auth:
  adminUser: admin
  existingSecret: keycloak-admin-password
  passwordSecretKey: password

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    memory: 1Gi

# Use embedded PostgreSQL for simplicity
postgresql:
  enabled: true
  auth:
    existingSecret: keycloak-postgresql-password
  primary:
    persistence:
      enabled: true
      size: 2Gi
      storageClass: local-path
    podSecurityContext:
      fsGroup: 1001
    containerSecurityContext:
      runAsUser: 1001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi

production: true

proxy: edge

extraEnvVars:
  - name: KC_HOSTNAME
    value: idp.rosta.dev
  - name: KC_HOSTNAME_ADMIN
    value: idp-admin.rosta.dev

ingress:
  enabled: true
  ingressClassName: traefik
  hostname: idp.rosta.dev
  extraHosts:
    - name: idp-admin.rosta.dev
  tls: true

# Health & readiness
readinessProbe:
  enabled: true
livenessProbe:
  enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
